# Specification for custom Rocq compilation flags.
# Syntax:
# - One flag per line with no leading/trailing blanks.
# - Empty lines and lines starting with '#' are ignored.

# Disable some warnings (for Rocq >= 9.2)

-w
-notation-for-abbreviation

-w
-ltac2-notation-for-abbreviation

-w
-implicit-create-hint-db

-w
-implicit-create-rewrite-hint-db

-w
-register-all

-w
-scheme-rewriting
