From subcomponents Require ring.
From Stdlib Require Arith.Arith.
From Stdlib Require Arith.Between.
From Stdlib Require Arith.Bool_nat.
From Stdlib Require Arith.Cantor.
From Stdlib Require Arith.Compare.
From Stdlib Require Arith.Compare_dec.
From Stdlib Require Arith.EqNat.
From Stdlib Require Arith.Euclid.
From Stdlib Require Arith.Factorial.
From Stdlib Require Arith.PeanoNat.
From Stdlib Require Arith.Peano_dec.
From Stdlib Require Arith.Wf_nat.
From Stdlib Require Arith.Zerob.
From Stdlib Require Numbers.NumPrelude.
From Stdlib Require Classes.SetoidDec.
