From subcomponents Require naturals.
From Stdlib Require Logic.IndefiniteDescription.
From Stdlib Require Logic.Classical_Pred_Type.
From Stdlib Require Logic.Classical_Prop.
From Stdlib Require Logic.ClassicalFacts.
From Stdlib Require Logic.Classical.
From Stdlib Require Logic.Epsilon.
From Stdlib Require Logic.ClassicalChoice.
From Stdlib Require Logic.Description.
From Stdlib Require Logic.ClassicalEpsilon.
From Stdlib Require Logic.ChoiceFacts.
From Stdlib Require Logic.PropExtensionality.
From Stdlib Require Logic.ClassicalDescription.
From Stdlib Require Logic.ClassicalUniqueChoice.
From Stdlib Require Logic.SetoidChoice.
From Stdlib Require Logic.Diaconescu.
