From subcomponents Require naturals.
From Stdlib Require Lists.List.
From Stdlib Require Classes.EquivDec.
From Stdlib Require Lists.ListDec.
From Stdlib Require Lists.Finite.
From Stdlib Require Lists.ListSet.
From Stdlib Require Lists.ListTactics.
From Stdlib Require Logic.WKL.
From Stdlib Require Sorting.Permutation.
