From subcomponents Require field.
From subcomponents Require rationals.
From Stdlib Require QArith.Qfield.
From Stdlib Require QArith.Qring.
From Stdlib Require micromega.DeclConstantZ.
From Stdlib Require micromega.DeclConstant.
From Stdlib Require micromega.QMicromega.
From Stdlib Require micromega.Lqa.
From Stdlib Require setoid_ring.Rings_Q.
