From subcomponents Require positive.
From Stdlib Require NArith.BinNatDef.
From Stdlib Require NArith.BinNat.
From Stdlib Require NArith.Nnat.
From Stdlib Require NArith.Ndiv_def.
From Stdlib Require NArith.Ndec.
From Stdlib Require NArith.Ngcd_def.
From Stdlib Require NArith.Nsqrt_def.
From Stdlib Require NArith.NArith_base.
