From subcomponents Require arith.
From subcomponents Require qarith.
From subcomponents Require classical_logic.
From subcomponents Require vectors.
From Stdlib Require Reals.Reals.
From Stdlib Require Reals.Abstract.ConstructivePower.
From Stdlib Require Reals.Abstract.ConstructiveMinMax.
From Stdlib Require Reals.Runcountable.
From Stdlib Require Reals.ClassicalConstructiveReals.
From Stdlib Require Reals.Machin.
From Stdlib Require Reals.Rminmax.
From Stdlib Require Reals.Rlogic.
From Stdlib Require Reals.Nsatz.
From Stdlib Require setoid_ring.Rings_R.
From Stdlib Require micromega.Psatz.
From Stdlib Require Numbers.DecimalR.
From Stdlib Require Numbers.HexadecimalR.
