From subcomponents Require integers.
From subcomponents Require lists.
From Stdlib Require setoid_ring.Ncring_polynom.
From Stdlib Require setoid_ring.Rings_Z.
From Stdlib Require setoid_ring.Ncring_initial.
From Stdlib Require setoid_ring.Ring_polynom.
From Stdlib Require setoid_ring.ZArithRing.
From Stdlib Require setoid_ring.Integral_domain.
From Stdlib Require setoid_ring.Ring_base.
From Stdlib Require setoid_ring.BinList.
From Stdlib Require setoid_ring.Ncring.
From Stdlib Require setoid_ring.Ring.
From Stdlib Require setoid_ring.Algebra_syntax.
From Stdlib Require setoid_ring.InitialRing.
From Stdlib Require setoid_ring.Cring.
From Stdlib Require setoid_ring.Ncring_tac.
From Stdlib Require setoid_ring.Ring_tac.
From Stdlib Require setoid_ring.ArithRing.
From Stdlib Require setoid_ring.NArithRing.
From Stdlib Require setoid_ring.Ring_theory.
From Stdlib Require nsatz.NsatzTactic.
From Stdlib Require nsatz.ENsatzTactic.
From Stdlib Require micromega.VarMap.
From Stdlib Require micromega.RingMicromega.
