From subcomponents Require classical_logic.
From Stdlib Require Sets.Partial_Order.
From Stdlib Require Sets.Multiset.
From Stdlib Require Sets.Uniset.
From Stdlib Require Sets.Relations_2.
From Stdlib Require Sets.Image.
From Stdlib Require Sets.Relations_3.
From Stdlib Require Sets.Relations_1.
From Stdlib Require Sets.Classical_sets.
From Stdlib Require Sets.Finite_sets.
From Stdlib Require Sets.Permut.
From Stdlib Require Sets.Integers.
From Stdlib Require Sets.Finite_sets_facts.
From Stdlib Require Sets.Powerset_facts.
From Stdlib Require Sets.Powerset.
From Stdlib Require Sets.Powerset_Classical_facts.
From Stdlib Require Sets.Ensembles.
From Stdlib Require Sets.Relations_1_facts.
From Stdlib Require Sets.Constructive_sets.
From Stdlib Require Sets.Infinite_sets.
From Stdlib Require Sets.Relations_2_facts.
From Stdlib Require Sets.Relations_3_facts.
From Stdlib Require Sets.Cpo.
