From subcomponents Require lists.
From Stdlib Require Wellfounded.Inclusion.
From Stdlib Require Wellfounded.Wellfounded.
From Stdlib Require Wellfounded.Union.
From Stdlib Require Wellfounded.Transitive_Closure.
From Stdlib Require Wellfounded.Well_Ordering.
From Stdlib Require Wellfounded.Inverse_Image.
From Stdlib Require Wellfounded.Disjoint_Union.
From Stdlib Require Wellfounded.Lexicographic_Product.
From Stdlib Require Wellfounded.Lexicographic_Exponentiation.
From Stdlib Require Wellfounded.List_Extension.
