name: Check duplicate files
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check for duplicate files
      run: dev/tools/check-duplicate-files.sh
